# -*- coding: utf-8 -*-
"""Sentiment Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Eb-CMYEF--i8-ZkZPlY5Jc9WGerXWqga
"""

pip install vaderSentiment

import pandas as pd
import datetime

import nltk
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Download the necessary NLTK data
nltk.download('punkt')
nltk.download('vader_lexicon')

twitter_data = pd.read_csv("/content/stock_tweets.csv")

twitter_data.head()

tweets = []

text = twitter_data["Tweet"]
text.head()

# Create an instance of the sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

# Define a function to extract the sentiment score for each tweet
def get_sentiment_score(text):
    return analyzer.polarity_scores(text)['compound']

# Apply the sentiment analysis function to the "Tweet" column
twitter_data['Sentiment Score'] = twitter_data['Tweet'].apply(get_sentiment_score)

twitter_data

# Filter the dataframe by the "Stock Name" column
stock_df = twitter_data.groupby('Stock Name').mean()

# Print the mean sentiment score for each stock
print(stock_df['Sentiment Score'])

twitter_data.head()

twitterWithScores = twitter_data

twitterWithScores['Date'] = pd.to_datetime(twitterWithScores['Date'])
twitterWithScores['Date'] = twitterWithScores['Date'].dt.date
twitterWithScores

positive = twitterWithScores[twitterWithScores["Sentiment Score"] > .5]
positive.head(15)

text = positive["Tweet"]
text.head(20)

noc = twitterWithScores[twitterWithScores['Stock Name'] == "NOC"]
noc

analyzer.lexicon.update({
    'conflict': 1.5,
    'violence': -1.5,
    'war': 2.0,
    'resolution': 1.5,
    'peacekeeping': 1.5,
})

# add negative words related to war
analyzer.lexicon.update({
    'atrocity': -2.0,
    'casualty': -1.5,
    'death': -2.0,
    'genocide': -2.5,
    'terrorism': -2.0,
})

textWar = "Since the Ukrainian war, Northrop Grumman Corporation, $NOC, has hit all-time highs, up 27%."
scores = analyzer.polarity_scores(textWar)["compound"]
scores

from google.colab import files
twitter_data.to_csv('twitterWithScores2.csv')
files.download('twitterWithScores2.csv')

stock_df.to_csv('stock_sentiment_data.csv')
files.download('stock_sentiment_data.csv')

import pandas as pd
from textblob import TextBlob

# Load the dataset
df = twitter_data

# Define a function to get the sentiment polarity score of each tweet
def get_sentiment(tweet):
    blob = TextBlob(tweet)
    return blob.sentiment.polarity

# Apply the sentiment function to each tweet in the dataset
df['sentiment(blob)'] = df['Tweet'].apply(get_sentiment)

# Visualize the distribution of sentiment scores
df['sentiment(blob)'].plot.hist(bins=20)

df